### ISSUE TITLE
how to open MoppyLib and MoppycontrolGUI in NebeansProjects

### ISSUE THREAD

**Issue by sunzero0123** [Sammy1Am/Moppy2#101]
<img width="445" alt="20200625_151258" src="https://user-images.githubusercontent.com/44018024/85665474-68855500-b6f6-11ea-874f-a35af72eaf25.png">
<img width="841" alt="20200625_152447" src="https://user-images.githubusercontent.com/44018024/85666958-09284480-b6f8-11ea-9277-1ccf22786835.png">

Do I need to create a new Netbenasprojects? 
Buildship Gradle Intergration Plugin installed in Eclipse.

**Comment by Sammy1Am** [comment]
I'm sorry it took so long to respond, my inbox got a little overfull this last week.

According to the [Gradle Support plugin page](http://plugins.netbeans.org/plugin/44510/gradle-support) :

> Allows opening directories containing a "build.gradle" file as a project in NetBeans. The opened project then can be used as a usual Java project.

So I think you'd go to "Open Project" and choose the `MoppyControlGUI` folder (and `MoppyLib`), and I think it should open fine.  I don't have access to NetBeans at the moment (and have just been using the command line gradle lately).
