### ISSUE TITLE
Error while Uploading: Error compiling for Arduino Uno, FL_FALLTHROUGH

### ISSUE THREAD

**Issue by LuzDerSchluz** [Sammy1Am/Moppy2#110]
Hi, i am getting this Error when trying to upload the sketch

`Arduino: 1.6.9 (Linux), Board: "Arduino/Genuino Uno"

In file included from sketch/.pio/libdeps/esp12e/FastLED/platforms/avr/fastled_avr.h:6:0,
                 from sketch/.pio/libdeps/esp12e/FastLED/platforms.h:39,
                 from sketch/.pio/libdeps/esp12e/FastLED/FastLED.h:52,
                 from sketch/.pio/libdeps/esp12e/FastLED/FastLED.cpp:2:
sketch/.pio/libdeps/esp12e/FastLED/platforms/avr/clockless_trinket.h: In static member function 'static void ClocklessController<DATA_PIN, T1, T2, T3, RGB_ORDER, XTRA0, FLIP, WAIT_TIME>::showRGBInternal(PixelController<RGB_ORDER>&)':
sketch/.pio/libdeps/esp12e/FastLED/platforms/avr/clockless_trinket.h:326:24: error: expected primary-expression before '__attribute__'
 #define FL_FALLTHROUGH __attribute__ ((fallthrough));
                        ^
sketch/.pio/libdeps/esp12e/FastLED/platforms/avr/clockless_trinket.h:409:55: note: in expansion of macro 'FL_FALLTHROUGH'
      case 4: _D2(0) LO1 _D3(0) HI1 _D1(1) QLO2(b0,0)  FL_FALLTHROUGH
                                                       ^
sketch/.pio/libdeps/esp12e/FastLED/platforms/avr/clockless_trinket.h:326:24: error: expected ';' before '__attribute__'
 #define FL_FALLTHROUGH __attribute__ ((fallthrough));
                        ^
sketch/.pio/libdeps/esp12e/FastLED/platforms/avr/clockless_trinket.h:409:55: note: in expansion of macro 'FL_FALLTHROUGH'
      case 4: _D2(0) LO1 _D3(0) HI1 _D1(1) QLO2(b0,0)  FL_FALLTHROUGH
                                                       ^
sketch/.pio/libdeps/esp12e/FastLED/platforms/avr/clockless_trinket.h:326:24: error: expected primary-expression before '__attribute__'
 #define FL_FALLTHROUGH __attribute__ ((fallthrough));
                        ^
sketch/.pio/libdeps/esp12e/FastLED/platforms/avr/clockless_trinket.h:410:55: note: in expansion of macro 'FL_FALLTHROUGH'
      case 3: _D2(0) LO1 _D3(0) HI1 _D1(1) QLO2(b0,0)  FL_FALLTHROUGH
                                                       ^
sketch/.pio/libdeps/esp12e/FastLED/platforms/avr/clockless_trinket.h:326:24: error: expected ';' before '__attribute__'
 #define FL_FALLTHROUGH __attribute__ ((fallthrough));
                        ^
sketch/.pio/libdeps/esp12e/FastLED/platforms/avr/clockless_trinket.h:410:55: note: in expansion of macro 'FL_FALLTHROUGH'
      case 3: _D2(0) LO1 _D3(0) HI1 _D1(1) QLO2(b0,0)  FL_FALLTHROUGH
                                                       ^
sketch/.pio/libdeps/esp12e/FastLED/platforms/avr/clockless_trinket.h:326:24: error: expected primary-expression before '__attribute__'
 #define FL_FALLTHROUGH __attribute__ ((fallthrough));
                        ^
sketch/.pio/libdeps/esp12e/FastLED/platforms/avr/clockless_trinket.h:411:55: note: in expansion of macro 'FL_FALLTHROUGH'
      case 2: _D2(0) LO1 _D3(0) HI1 _D1(1) QLO2(b0,0)  FL_FALLTHROUGH
                                                       ^
sketch/.pio/libdeps/esp12e/FastLED/platforms/avr/clockless_trinket.h:326:24: error: expected ';' before '__attribute__'
 #define FL_FALLTHROUGH __attribute__ ((fallthrough));
                        ^
sketch/.pio/libdeps/esp12e/FastLED/platforms/avr/clockless_trinket.h:411:55: note: in expansion of macro 'FL_FALLTHROUGH'
      case 2: _D2(0) LO1 _D3(0) HI1 _D1(1) QLO2(b0,0)  FL_FALLTHROUGH
                                                       ^
sketch/.pio/libdeps/esp12e/FastLED/platforms/avr/clockless_trinket.h:326:24: error: expected primary-expression before '__attribute__'
 #define FL_FALLTHROUGH __attribute__ ((fallthrough));
                        ^
sketch/.pio/libdeps/esp12e/FastLED/platforms/avr/clockless_trinket.h:425:55: note: in expansion of macro 'FL_FALLTHROUGH'
      case 4: _D2(0) LO1 _D3(0) HI1 _D1(1) QLO2(b0,0)  FL_FALLTHROUGH
                                                       ^
sketch/.pio/libdeps/esp12e/FastLED/platforms/avr/clockless_trinket.h:326:24: error: expected ';' before '__attribute__'
 #define FL_FALLTHROUGH __attribute__ ((fallthrough));
                        ^
sketch/.pio/libdeps/esp12e/FastLED/platforms/avr/clockless_trinket.h:425:55: note: in expansion of macro 'FL_FALLTHROUGH'
      case 4: _D2(0) LO1 _D3(0) HI1 _D1(1) QLO2(b0,0)  FL_FALLTHROUGH
                                                       ^
sketch/.pio/libdeps/esp12e/FastLED/platforms/avr/clockless_trinket.h:326:24: error: expected primary-expression before '__attribute__'
 #define FL_FALLTHROUGH __attribute__ ((fallthrough));
                        ^
sketch/.pio/libdeps/esp12e/FastLED/platforms/avr/clockless_trinket.h:426:55: note: in expansion of macro 'FL_FALLTHROUGH'
      case 3: _D2(0) LO1 _D3(0) HI1 _D1(1) QLO2(b0,0)  FL_FALLTHROUGH
                                                       ^
sketch/.pio/libdeps/esp12e/FastLED/platforms/avr/clockless_trinket.h:326:24: error: expected ';' before '__attribute__'
 #define FL_FALLTHROUGH __attribute__ ((fallthrough));
                        ^
sketch/.pio/libdeps/esp12e/FastLED/platforms/avr/clockless_trinket.h:426:55: note: in expansion of macro 'FL_FALLTHROUGH'
      case 3: _D2(0) LO1 _D3(0) HI1 _D1(1) QLO2(b0,0)  FL_FALLTHROUGH
                                                       ^
sketch/.pio/libdeps/esp12e/FastLED/platforms/avr/clockless_trinket.h:326:24: error: expected primary-expression before '__attribute__'
 #define FL_FALLTHROUGH __attribute__ ((fallthrough));
                        ^
sketch/.pio/libdeps/esp12e/FastLED/platforms/avr/clockless_trinket.h:427:55: note: in expansion of macro 'FL_FALLTHROUGH'
      case 2: _D2(0) LO1 _D3(0) HI1 _D1(1) QLO2(b0,0)  FL_FALLTHROUGH
                                                       ^
sketch/.pio/libdeps/esp12e/FastLED/platforms/avr/clockless_trinket.h:326:24: error: expected ';' before '__attribute__'
 #define FL_FALLTHROUGH __attribute__ ((fallthrough));
                        ^
sketch/.pio/libdeps/esp12e/FastLED/platforms/avr/clockless_trinket.h:427:55: note: in expansion of macro 'FL_FALLTHROUGH'
      case 2: _D2(0) LO1 _D3(0) HI1 _D1(1) QLO2(b0,0)  FL_FALLTHROUGH
                                                       ^
sketch/.pio/libdeps/esp12e/FastLED/platforms/avr/clockless_trinket.h:326:24: error: expected primary-expression before '__attribute__'
 #define FL_FALLTHROUGH __attribute__ ((fallthrough));
                        ^
sketch/.pio/libdeps/esp12e/FastLED/platforms/avr/clockless_trinket.h:444:55: note: in expansion of macro 'FL_FALLTHROUGH'
      case 4: _D2(0) LO1 _D3(0) HI1 _D1(1) QLO2(b0,0)  FL_FALLTHROUGH
                                                       ^
sketch/.pio/libdeps/esp12e/FastLED/platforms/avr/clockless_trinket.h:326:24: error: expected ';' before '__attribute__'
 #define FL_FALLTHROUGH __attribute__ ((fallthrough));
                        ^
sketch/.pio/libdeps/esp12e/FastLED/platforms/avr/clockless_trinket.h:444:55: note: in expansion of macro 'FL_FALLTHROUGH'
      case 4: _D2(0) LO1 _D3(0) HI1 _D1(1) QLO2(b0,0)  FL_FALLTHROUGH
                                                       ^
sketch/.pio/libdeps/esp12e/FastLED/platforms/avr/clockless_trinket.h:326:24: error: expected primary-expression before '__attribute__'
 #define FL_FALLTHROUGH __attribute__ ((fallthrough));
                        ^
sketch/.pio/libdeps/esp12e/FastLED/platforms/avr/clockless_trinket.h:445:55: note: in expansion of macro 'FL_FALLTHROUGH'
      case 3: _D2(0) LO1 _D3(0) HI1 _D1(1) QLO2(b0,0)  FL_FALLTHROUGH
                                                       ^
sketch/.pio/libdeps/esp12e/FastLED/platforms/avr/clockless_trinket.h:326:24: error: expected ';' before '__attribute__'
 #define FL_FALLTHROUGH __attribute__ ((fallthrough));
                        ^
sketch/.pio/libdeps/esp12e/FastLED/platforms/avr/clockless_trinket.h:445:55: note: in expansion of macro 'FL_FALLTHROUGH'
      case 3: _D2(0) LO1 _D3(0) HI1 _D1(1) QLO2(b0,0)  FL_FALLTHROUGH
                                                       ^
sketch/.pio/libdeps/esp12e/FastLED/platforms/avr/clockless_trinket.h:326:24: error: expected primary-expression before '__attribute__'
 #define FL_FALLTHROUGH __attribute__ ((fallthrough));
                        ^
sketch/.pio/libdeps/esp12e/FastLED/platforms/avr/clockless_trinket.h:446:55: note: in expansion of macro 'FL_FALLTHROUGH'
      case 2: _D2(0) LO1 _D3(0) HI1 _D1(1) QLO2(b0,0)  FL_FALLTHROUGH
                                                       ^
sketch/.pio/libdeps/esp12e/FastLED/platforms/avr/clockless_trinket.h:326:24: error: expected ';' before '__attribute__'
 #define FL_FALLTHROUGH __attribute__ ((fallthrough));
                        ^
sketch/.pio/libdeps/esp12e/FastLED/platforms/avr/clockless_trinket.h:446:55: note: in expansion of macro 'FL_FALLTHROUGH'
      case 2: _D2(0) LO1 _D3(0) HI1 _D1(1) QLO2(b0,0)  FL_FALLTHROUGH
                                                       ^
exit status 1
Error compiling for board Arduino/Genuino Uno.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

Can anyone help me? Thanks in advance.

**Comment by Sammy1Am** [comment]
This looks like some sort of compatibility issue between the FastLED library and the Arduino IDE.  I.e. there's no Moppy anything in there as far as I can tell.  Arduino 1.6.9 is like 2.5 years old though, so maybe try again with the latest IDE.  Alternatively, you could try with a slightly older FastLED in case one of their recent changes broke something.
