### ISSUE TITLE
Play lists

### ISSUE THREAD

**Issue by Amakes** [Sammy1Am/Moppy2#116]
Is there any way to make a playlist so it can play over a period of time without having to select a file after each song ends?

**Comment by Sammy1Am** [comment]
Yup!  The [latest release](https://github.com/Sammy1Am/Moppy2/releases/tag/2.1.0) already has that functionality.  Is there something there that's not working correctly, or are you using an older release?

**Comment by Amakes** [comment]
I think I was just using an older version, Thanks
