### ISSUE TITLE
moppycontrolgui.bat closes

### ISSUE THREAD

**Issue by SaT77** [Sammy1Am/Moppy2#129]
![mopppy](https://user-images.githubusercontent.com/66516016/110227898-148a6b80-7f27-11eb-8919-ca03f01eb8ce.JPG)

**Comment by Sammy1Am** [comment]
You need a more recent version of Java.

**Comment by SaT77** [comment]
which version of java i should install?

**Comment by Sammy1Am** [comment]
Unless you have a specific reason not to, the most recently released
version is a good bet.  I think it's 15 currently.

**Comment by SaT77** [comment]
i installed jre-8u281(latest), and it too recent

**Comment by SaT77** [comment]
![mopppy](https://user-images.githubusercontent.com/66516016/110231369-9edfc900-7f41-11eb-9f90-7feb54f02b82.JPG)

**Comment by Sammy1Am** [comment]
jre-8u281 is Java 8.  Java 15 is the latest.

**Comment by SaT77** [comment]
ty
