### ISSUE TITLE
Can't find where to download the moppy control gui 

### ISSUE THREAD

**Issue by DurpyDuck** [Sammy1Am/Moppy2#141]
Hi I'm just in the process of setting up for the first time, I have the Uno setup and working with the floppy drive playing the boot tone, but after that I'm completely lost on what to do.

I'm sorry if this is a stupid question, I've tried looking this up online and have come across several tutorials which aren't helping.

Thanks for you reply.
![Issue](https://user-images.githubusercontent.com/88201093/127748155-c3971626-9a37-4b1d-9071-b027d708795e.JPG)

**Comment by DurpyDuck** [comment]
I'm just stupid, I got it working now.

**Comment by Sammy1Am** [comment]
GitHub's layout is weird sometimes, no worries :P
