### ISSUE TITLE
Problem uploading to board error

### ISSUE THREAD

**Issue by khaled040940** [Sammy1Am/Moppy2#151]
I'm trying to upload the program in the Arduino IDE but when I do, I wait a while then I get this error shown in the picture below. Please help <3
![image](![145408180-eada0676-f54d-47c3-85fe-60383a6d1974](https://user-images.githubusercontent.com/95864539/145408298-4c362d81-a406-45ef-9bc4-234188cdcd5e.png))

**Comment by DJthefirst** [comment]
the image does not load for some reason.

**Comment by khaled040940** [comment]
![image](https://user-images.githubusercontent.com/95864539/145536942-1108c16c-2884-4082-b173-8e6fcf9046db.png)
here

**Comment by Sammy1Am** [comment]
Looks like an error communicating with the board (but not anything to do
with Moppy code).  What kind of board are you using?  How are you
connecting to it?

(Google might be of some help here too)

**Comment by khaled040940** [comment]
I honestly don't quite under what you mean by what kind of board I'm using. But here's my setup, I'm using this KENTEK 680 watts power supply that's connected to a power supply tester to get it working. Then I connected my floppy to the power supply and connected a jumper wire between pin 11 and 12, light turned on. So far so good. But then after I got my Arduino and connected the step and direction pin to it, I clicked reset nothing happens, and when I tried uploading the arduino in the Arduino IDE, I got that error, here a picture to demonstrate. 
![image](https://user-images.githubusercontent.com/95864539/145559403-b624183f-a77e-4610-b40a-f45d9660d19c.png)

**Comment by khaled040940** [comment]
ok I think I figured something out, I realized I was connected to COM1 instead of COM4( Arduino UNO) in the tools menu, but now another error occurred when trying to upload it 
![image](https://user-images.githubusercontent.com/95864539/145561387-083cdf24-580e-4579-ba8c-ae83771dc2c6.png)
![image](https://user-images.githubusercontent.com/95864539/145561399-aa964916-1c9c-4a92-a9eb-83755f8b2cec.png)

**Comment by Sammy1Am** [comment]
Looks like the board you are using is an Arduino Uno; your computer still
seems to be having some trouble communicating with the Arduino.

Google is your friend for that error too (I can try doing a search myself
next time I'm at a computer, but it's not a Moppy-specific issue).

**Comment by khaled040940** [comment]
Alright, I'll try to figure something out, it worked for me once but never again after trying to upload a million times later. but my floppy disk hates me and doesn't wanna play those 4 notes I've been waiting for.

**Comment by khaled040940** [comment]
NEVERMIND finally it worked, I fixed it finally. thanks a lot!
