### ISSUE TITLE
Error compiling for UNO

### ISSUE THREAD

**Issue by COMMODOREAMIGA1000** [Sammy1Am/Moppy2#164]
Arduino: 1.8.19 (Windows 10), Board: "Arduino Uno"

C:\Users\[REDACTED FOR PRIVACY]\Desktop\Moppy2-Arduino\src\MoppyInstruments\MoppyTimer.cpp:4:10: fatal error: TimerOne.h: No such file or directory

 #include <TimerOne.h>

          ^~~~~~~~~~~~

compilation terminated.

exit status 1

Error compiling for board Arduino Uno.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by WeeMellowToby** [comment]
you need to add/install timerone.h to the project

**Comment by COMMODOREAMIGA1000** [comment]
I'm new to this; could you explain how I do that?

**Comment by Sammy1Am** [comment]
Here are instructions for installing Arduino Libraries, just select the TimerOne library and install it:
https://docs.arduino.cc/software/ide-v1/tutorials/installing-libraries
