### ISSUE TITLE
I can't upload project to arduino

### ISSUE THREAD

**Issue by Yaoofi** [Sammy1Am/Moppy2#181]
When I am trying to upload the project to my _arduino uno_ I am getting this message

_"Compilation error: TimerOne.h: No such file or directory"_

and I can not upload it to Arduino because of this error.
I was trying it on two PC's and it won't work on any of this so please help me

**Comment by WeeMellowToby** [comment]
you need to install the timerone library

**Comment by Yaoofi** [comment]
Thanks, it's working. Now I feel so stupid

**Comment by Sammy1Am** [comment]
Nah, no worries.  It's hard to tell sometimes if it's a issue with the
Moppy project, or just a general issue like installing a library.  Glad
it's working!
