### ISSUE TITLE
MoppyGUI wont connect to arduino

### ISSUE THREAD

**Issue by Wev-Oppy** [Sammy1Am/Moppy2#197]
When i click the COM box all it says is

![Captu64875re](https://github.com/Sammy1Am/Moppy2/assets/139383739/0185cf23-55df-4304-80a4-bb8fbf5f79fe)

The arduino is plugged in and the .ino sketch is uploaded.
The 239 box does work though.

![Capt3453ure](https://github.com/Sammy1Am/Moppy2/assets/139383739/95e71731-a5f0-413d-9f98-280c33256c46)

**Comment by Wev-Oppy** [comment]
Hold up never mind it just started working.
I guess just restarting my computer worked.

**Comment by Sammy1Am** [comment]
"Have you tried turning it off and on aga--" oh. 😉

Glad you got it working!
