### ISSUE TITLE
MoppyControlGUI.bat crashes

### ISSUE THREAD

**Issue by OlegMoore1488** [Sammy1Am/Moppy2#203]
Hi, I have a problem with moppy2.
When starting the bat file, it crashes, I did everything as written in the guide.

**Comment by Sammy1Am** [comment]
Try running the .bat file from the command line so you can see which error
is being reported.  Most likely you either need a newer version of Java, or
JAVA_HOME is not set correctly.

**Comment by OlegMoore1488** [comment]
![зображення_2023-11-05_235303111](https://github.com/Sammy1Am/Moppy2/assets/149973166/cb762d7b-64ac-4ff8-87e0-a7001c92f792)
here is the error itself

**Comment by Sammy1Am** [comment]
You are attempting to run Moppy with Java 8.  You need at least Java 11 (but even 11 is pretty old, you should just use the latest release).

**Comment by OlegMoore1488** [comment]
installed the latest version of Java (21) it still does not start
![image](https://github.com/Sammy1Am/Moppy2/assets/149973166/26b01514-8a02-4db3-9e00-16cedfcd4f31)

**Comment by Sammy1Am** [comment]
Java 8 is still installed and is either set in JAVA_HOME or in your path variable.  Sometimes uninstalling Java 8 will resolve this, though you then might have an error about JAVA_HOME not being set and will need to set it manually anyway.

**Comment by OlegMoore1488** [comment]
I deleted all old versions of Java, leaving only Java version 21, but it still does not start
![зображення_2023-11-06_003014841](https://github.com/Sammy1Am/Moppy2/assets/149973166/b09a67bc-e17d-4075-8795-f330f6b56144)
what else could be the problem?

**Comment by Sammy1Am** [comment]
You missed a version of Java 8.

Try `echo %JAVA_HOME%` in a command prompt and let me know what the output is.

**Comment by OlegMoore1488** [comment]
![image](https://github.com/Sammy1Am/Moppy2/assets/149973166/f8e31753-2d6f-4586-9e1e-e11f09606cd1)
I don't know what the problem is, I deleted the 8th version of Java completely, but in the console it says that it still exists, but if you go down the path, there is nothing
![image](https://github.com/Sammy1Am/Moppy2/assets/149973166/b43b17b8-0df9-43a8-892a-d5730e713669)

**Comment by Sammy1Am** [comment]
Weird.  There's still a Java 8 somewhere because Java 8 is what's outputting the error message you're getting (it would say something other than `52.0` if it were not Java 8).

Perhaps try setting your `JAVA_HOME` variable to point to the Java 21 installation.

**Comment by OlegMoore1488** [comment]
i already fixed everything, everything works perfectly.
thanks for the help
