### ISSUE TITLE
.Bat file not openning correctly

### ISSUE THREAD

**Issue by margantsovka6** [Sammy1Am/Moppy2#213]
UPD: It works! I reinstalled java to 21 version.

Have issues when opening GUI file. I dont know java, so i just dont understad how to open it correctly. The floppy making startup sound, so i think i did the arduino part well. How can i open midi? When opening .bat file this window appears. What i need to do?
![image](https://github.com/Sammy1Am/Moppy2/assets/132107606/72c0312b-2c76-4ef0-be33-15c5c55e0541)

**Comment by Sammy1Am** [comment]
Ah, yeah, tracking this in #210 , I guess something changed in 22 that breaks things.
