### ISSUE TITLE
Are there updated Instructions?

### ISSUE THREAD

**Issue by ubotdude** [Sammy1Am/Moppy2#75]
I read on someone's youtube page that the instructions had been updated eliminating Netbeans.

Is that the case?  I almost have everything on hand to start so I want to ensure that I am following the most accurate instructions.

Thanks for maintaining project!

Buddy

**Comment by SammyIAm** [comment]
If you download zips from the "Releases" page on GitHub, there's no IDE
required just to run the MoppyControlGUI.  (You'll still need the Arduino
IDE to flash that firmware)

If you want to build the project from source, you'll need a
gradle-compatible build system, but NetBeans itself is no longer the only
option.
