### ISSUE TITLE
ControllerGUI

### ISSUE THREAD

**Issue by Exy25** [Sammy1Am/Moppy2#82]
Hello I dont know how to open controllerGUI because in the wiki is that in the folder is some run.bat
file. So i can run it with it. But I dont see it
Can you help me please???

**Comment by SammyIAm** [comment]
Are you downloading the zip files from the [releases](https://github.com/SammyIAm/Moppy2/releases) page?  The `.bat` file should be in the `bin` directory there.  Make sure you right-click on the .zip file and "Unblock" it before you unzip it or Windows might refuse to run Java.
