### ISSUE TITLE
NetBeans Gradle version error

### ISSUE THREAD

**Issue by krashone** [Sammy1Am/Moppy2#88]
now gives me this mistake

JAVA_HOME="C:\Program Files\Java\jdk-13.0.2"
cd C:\Users\krash\3D Objects\Floppy Music\Moppy2-master\Java\MoppyControlGUI; C:\Users\krash.gradle\wrapper\dists\gradle-4.10.2-bin\cghg6c4gf4vkiutgsab8yrnwv\gradle-4.10.2\bin\gradle --configure-on-demand -x check run
Configuration on demand is an incubating feature.

Task :MoppyLib:compileJava FAILED

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':MoppyLib:compileJava'.
java.lang.ExceptionInInitializerError

Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 0s
1 actionable task: 1 executed

**Comment by SammyIAm** [comment]
It appears that the version of Gradle that you're using (4.10.2) doesn't support Java 13.  You'll either need to downgrade your JDK (probably to Java 10, but maybe Java 9) for compilation with Gradle, or update Gradle to at least 6.0 (though it looks like the NetBeans plugin only goes as high as Gradle 5).

Also sounds like I might be using some "deprecated Gradle features", but it's not very specific as to what those are.  Someday I'll have NetBeans set up again and might fix / update some of this so it's more straightforward, but in the meantime you're going to have to do a little troubleshooting yourself unfortunately.

Something else to try potentially is installing a standalone version of gradle to run outside of NetBeans for building and running the program (NetBeans should still work for editing).
