### ISSUE TITLE
Time label showing incorrect value when dragging slider using mouse

### ISSUE THREAD

**Issue by zdimension** [Sammy1Am/Moppy2#89]
Before dragging:
![image](https://user-images.githubusercontent.com/4533568/75243923-175a6880-57cb-11ea-95c3-982d4bad49ef.png)
While dragging:
![image](https://user-images.githubusercontent.com/4533568/75243960-293c0b80-57cb-11ea-902b-1d47e760130a.png)
When the mouse button is released, the incorrect value gets replaced by the correct timecode.

**Comment by Sammy1Am** [comment]
Fixed with c1400d7
